[versions]
agp = "8.13.0"
grgit = "5.2.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }




